services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_agrix
    ports:
      - "8080:8080"
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agrixdatabase
